name: Package setup command

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup node v${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: yarn install
    - run: yarn setup
