name: test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.9]
    steps:
      - uses: actions/checkout@v2
      - name: npm i
        run: npm i
      - name: npm run setup
        run: npm run setup
      - name: npm run lint
        run: npm run lint
      - name: npm run type
        run: npm run type
      - name: npm run test
        run: npm run test
